FROM golang:1.15
ARG version
WORKDIR work
COPY go.* .
COPY ../pkg pkg/
COPY ../vendor vendor/
COPY services/user/ services/user/
RUN GO111MODULE=on GOFLAGS=-mod=vendor CGO_ENABLED=0 GOOS=linux go build -v -ldflags "-X __PACKAGE__/services/user/main.version=$version" -a -installsuffix cgo -o user .

FROM alpine:3.12
RUN apk --no-cache add ca-certificates
WORKDIR /user/
COPY --from=0 work/services/user .
ENTRYPOINT ["/user/user"]
CMD ["run", "--logtostderr"]
